### ISSUE TITLE
Is webpack 3 supporter ?

### ISSUE THREAD

**Issue by SeanSilke** [smelukov/statoscope#22]
The documentation stands "Webpack 1.x/2.x plugin" does it means that version 3 is not supported?
Is there plans to support 3 version?

**Comment by smelukov** [comment]
WRA not tested with Webpack 3 yet.
Feel free to use WRA with Webpack 3.
Just let me know if something is not working properly.

**Comment by ramonrf** [comment]
I got this error on a Webpack 3 setup

<img width="180" alt="screen shot 2018-03-25 at 4 28 52 am" src="https://user-images.githubusercontent.com/6119839/37874103-26da1158-2fe5-11e8-9908-c7c296407003.png">

**Comment by popbee** [comment]
With Webpack 3, can work aroudn the connection lost (just refresh the page). But while running, I get the following error which stops webpack completely:
```
DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
C:\dev\reactjs\node_modules\bluebird\js\release\async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'context' of undefined
    at makeRelative (C:\dev\reactjs\node_modules\webpack-runtime-analyzer\src\plugin\index.js:100:32)
    at getModuleId (C:\dev\reactjs\node_modules\webpack-runtime-analyzer\src\plugin\index.js:116:29)
    at C:\dev\reactjs\node_modules\webpack-runtime-analyzer\src\plugin\index.js:330:32
    at Array.map (<anonymous>)
    at C:\dev\reactjs\node_modules\webpack-runtime-analyzer\src\plugin\index.js:329:22
    at Array.map (<anonymous>)
    at Compiler.<anonymous> (C:\dev\reactjs\node_modules\webpack-runtime-analyzer\src\plugin\index.js:284:39)
    at next (C:\dev\reactjs\node_modules\tapable\lib\Tapable.js:204:14)
    at Compiler.compiler.plugin (C:\dev\reactjs\node_modules\webpack\lib\ProgressPlugin.js:128:5)
    at next (C:\dev\reactjs\node_modules\tapable\lib\Tapable.js:204:14)
    at ForkTsCheckerWebpackPlugin.emitCallback (C:\dev\reactjs\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:311:13)
    at Compiler.<anonymous> (C:\dev\reactjs\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:177:23)
    at next (C:\dev\reactjs\node_modules\tapable\lib\Tapable.js:204:14)
    at ManifestPlugin.<anonymous> (C:\dev\reactjs\node_modules\webpack-manifest-plugin\lib\plugin.js:161:5)
    at next (C:\dev\reactjs\node_modules\tapable\lib\Tapable.js:204:14)
    at C:\dev\reactjs\node_modules\html-webpack-plugin\index.js:204:9```

**Comment by smelukov** [comment]
Now we have a brand new analyzer in this repo, please check this out 😀
